import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import Nav from "../components/Nav";
import Results from "../components/Results";
import requests from "../utils/requests";
import { BrowserRouter as Router, Switch, Route } from "react-router-dom";
import { auth } from "../components/firebase";
import { useStateValues } from "../components/StateProvider";
import { useEffect } from "react";

export default function Home({ results }) {
  const [{ _ }, dispatch] = useStateValues();

  console.log(results[3].rating.rate.toFixed(0));

  useEffect(() => {
    //will only run once when the app component loads
    auth.onAuthStateChanged((authUser) => {
      console.log("thu user is", authUser);
      if (authUser) {
        dispatch({
          type: "SET_USER",
          user: authUser,
        });
      } else {
        dispatch({
          type: "SET_USER",
          user: null,
        });
      }
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Agri</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/AGRI (1).ico" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const category = context.query.category;

  const response = await fetch(
    `https://fakestoreapi.com/products${
      requests[category]?.url || requests.fetchALL.url
    }`
  );
  const results = await response.json();

  return {
    props: {
      results,
    },
  };
};
